name: testing
on: push
env:
  INSTALL_REQUIREMENTS: pip3 install -r requirements.txt
  FLASK_RUN: nohup python -m flask run
  PYTEST_RUN: pytest tests/test_app_instance.py tests/test_authentication.py tests/test_channels.py tests/test_socketio.py

jobs:
  unit_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      - name: Run pytest for unit test
        run: |
          $INSTALL_REQUIREMENTS         
          pip install -e . 
          $PYTEST_RUN

  e2e_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      - name: Prepare Selenium
        uses: nanasess/setup-chromedriver@v1.0.5
        run: sudo apt install firefox-geckodriver
      - name: Start flask app
        run: |
          $INSTALL_REQUIREMENTS          
          $FLASK_RUN
        env:
          FLASK_APP: flackt
          FLASK_ENV: development
          MOZ_HEADLESS: '1'
      - name: Start XVFB
        run: |
          Xvfb :99 &
      - name: Run selenium test
        run: |
          pip install -e .
          pytest tests/test_ui.py
        env:
          DISPLAY: :99
